version: '3.8'
services:
  postgres:
    container_name: db
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=helloworld
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: