version: '3.8'
services:
  postgres:
    container_name: db
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=helloworld
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  app-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=dev
      - DATABASE_URL=postgresql://blog:helloworld@postgres:5432/hibitica_db
    depends_on:
      - postgres
volumes:
  postgres: