GET http://localhost:8000/user
Content-Type: application/json

{"email":"ten@gmail.com"}

####
GET http://localhost:8000/user/1673221f-7e00-4f09-9666-54a4170909f1
Content-Type: application/json

{"email":"ten@gmail.com"}

####
POST http://localhost:8000/user
Content-Type: application/json

{
    "name":"shino",
    "fname":"shino",
    "lname":"mon",
    "username":"shino",
    "email":"shino@gmail.com",
    "password":"1234",
    "intro":"Hello world"
}
####
PATCH  http://localhost:8000/user/1673221f-7e00-4f09-9666-54a4170909f1
Content-Type: application/json

{
    "intro":"Hello world"
}

####
DELETE  http://localhost:8000/user/1673221f-7e00-4f09-9666-54a4170909f1
Content-Type: application/json
