#user
###
GET http://localhost:8000/user
Content-Type: application/json

####
GET http://localhost:8000/user/1673221f-7e00-4f09-9666-54a4170909f1
Content-Type: application/json

{"email":"ten@gmail.com"}

####
POST http://localhost:8000/user/register
Content-Type: application/json

{
    "name":"shino",
    "fname":"shino",
    "lname":"mon",
    "username":"vvvv",
    "email":"vvvv@gmail.com",
    "password":"hhhhhh",
    "intro":"Hello world"
}
####
POST http://localhost:8000/user/login
Content-Type: application/json

{
    "name":"shino",
    "fname":"shino",
    "lname":"mon",
    "email":"vvvv@gmail.com",
    "password":"hhhhhh",
    "intro":"Hello world"
}
####
PATCH  http://localhost:8000/user/1673221f-7e00-4f09-9666-54a4170909f1
Content-Type: application/json

{
    "intro":"Hello world"
}

####
DELETE  http://localhost:8000/user/1673221f-7e00-4f09-9666-54a4170909f1
Content-Type: application/json

#----------------------------------------------------
#category
###
GET http://localhost:8000/category
Content-Type: application/json

####
GET http://localhost:8000/category/1673221f-7e00-4f09-9666-54a4170909f1
Content-Type: application/json

####
POST http://localhost:8000/category
Content-Type: application/json

{
    "title":"masda", "content":"" ,"parentId":"1b597981-ffda-423d-9527-0c2a5bf8663b"
}
####
PATCH  http://localhost:8000/category/1673221f-7e00-4f09-9666-54a4170909f1
Content-Type: application/json

{
    "intro":"Hello world"
}


#----------------------------------------------------
#tag
###
GET http://localhost:8000/tag
Content-Type: application/json

####
GET http://localhost:8000/tag/1673221f-7e00-4f09-9666-54a4170909f1
Content-Type: application/json

####
POST http://localhost:8000/tag
Content-Type: application/json

{
    "title":"greeting", "content":"greeting world"
}

####
PATCH  http://localhost:8000/tag/1673221f-7e00-4f09-9666-54a4170909f1
Content-Type: application/json

{
    "intro":"Hello world"
}


#----------------------------------------------------
#post
###
GET http://localhost:8000/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NGZjMmQ4Ni00ZGE0LTQzYTMtYmRjYi1jMWE5MDhlZGJlNjYiLCJ1c2VybmFtZSI6InZ2dnYiLCJpYXQiOjE2OTAyMDc2NzB9.840Wi4_C7hf7Eir360vwwrhmVKsixka29KNAoIJ9ZCs


####
GET http://localhost:8000/post/1673221f-7e00-4f09-9666-54a4170909f1
Content-Type: application/json

####
POST http://localhost:8000/post
Content-Type: application/json

{
    "title":"Test post data", "content":"Hi this is a sample blog ,greeting world","published":true ,"authorId":"724284aa-5232-4858-876a-95fa161281d0"
}

####
PATCH  http://localhost:8000/post/1673221f-7e00-4f09-9666-54a4170909f1
Content-Type: application/json

{
    "intro":"Hello world"
}

#----------------------------------------------------
#post_category
###
GET http://localhost:8000/post_category
Content-Type: application/json

####
GET http://localhost:8000/post_category/1673221f-7e00-4f09-9666-54a4170909f1
Content-Type: application/json

####
POST http://localhost:8000/post_category
Content-Type: application/json

{
  "postId":"fd892246-0e12-42d1-8e7b-e73fb09d0894", "categoryId":"46d3f3c1-dd67-449a-8930-08a03e0ea874"
}

####
PATCH  http://localhost:8000/post_category/1673221f-7e00-4f09-9666-54a4170909f1
Content-Type: application/json

{
    "intro":"Hello world"
}

#----------------------------------------------------
#post_tag
###
GET http://localhost:8000/post_tag
Content-Type: application/json

####
GET http://localhost:8000/post_tag/1673221f-7e00-4f09-9666-54a4170909f1
Content-Type: application/json

####
POST http://localhost:8000/post_tag
Content-Type: application/json

{
  "postId":"fd892246-0e12-42d1-8e7b-e73fb09d0894", "tagId":"58e753b6-c987-4fe6-8bc2-dcc97e1b72c3"
}

####
PATCH  http://localhost:8000/post_tag/1673221f-7e00-4f09-9666-54a4170909f1
Content-Type: application/json

{
    "intro":"Hello world"
}

#----------------------------------------------------
#post_comment
###
GET http://localhost:8000/post_comment
Content-Type: application/json

####
GET http://localhost:8000/post_comment/1673221f-7e00-4f09-9666-54a4170909f1
Content-Type: application/json

####
POST http://localhost:8000/post_comment
Content-Type: application/json

{
  "postId":"fd892246-0e12-42d1-8e7b-e73fb09d0894", 
  "title":"good",
  "content":"goooooooooo",
  "authorId":"724284aa-5232-4858-876a-95fa161281d0"

}

####
PATCH  http://localhost:8000/post_comment/1673221f-7e00-4f09-9666-54a4170909f1
Content-Type: application/json

{
    "intro":"Hello world"
}
